<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="icon" href="../images/favicon.svg">
        <link rel="stylesheet" href="../css/bootstrap-icons.css">
        <link rel="stylesheet" href="../css/bootstrap.min.css">
        <link rel="stylesheet" href="../css/custom_styles.css">
        <title>OSBB HD4 | Contacts</title>
    </head>

    <body>
        <#include "header.ftlh">

        <main>
            <div class="container text-center">
                <div class="header my-5">
                    <h1>OSBB management & staff </h1>
                    <p class="text-muted">Contacts to resolve issues of OSBB functioning</p>
                </div>
                <div class="row">
                    <div class="col-lg-4">
                        <div class="img-block mb-5">
                            <img src="images/head_of_OSBB.png" class="img-fluid  img-thumbnail rounded-circle" alt="image1">
                            <div class="content mt-2">
                                <h4>Jane Doe</h4>
                                <p class="text-muted">Head of OSBB "Heroiv Dnipra 4"</p>
                                <p><i class="bi bi-at color-marker-blue"></i><a href="mailto:osbbhd4@gmail.com" class="text-reset text-decoration-none"> osbbhd4@gmail.com</a></p>
                                <p><i class="bi bi-telephone color-marker-blue"></i> (099) 999-99-99</p>
                                <p><i class="bi bi-watch color-marker-blue"></i> 9.00 - 18.00, Mon - Fri</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="img-block mb-5">
                            <img src="images/accountant_of_OSBB.png" class="img-fluid  img-thumbnail rounded-circle" alt="image1">
                            <div class="content mt-2">
                                <h4>Sarah J. Connor</h4>
                                <p class="text-muted">Accountant of OSBB "Heroiv Dnipra 4"</p>
                                <p><i class="bi bi-at color-marker-blue"></i><a href="mailto:osbbhd4@gmail.com" class="text-reset text-decoration-none"> osbbhd4@gmail.com</a></p>
                                <p><i class="bi bi-telephone color-marker-blue"></i> (098) 888-88-88</p>
                                <p><i class="bi bi-watch color-marker-blue"></i> 9.00 - 18.00, Mon - Fri</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="img-block mb-5">
                            <img src="images/engineer_of_OSBB.png" class="img-fluid  img-thumbnail rounded-circle" alt="image1">
                            <div class="content mt-2">
                                <h4>Bender Bending Rodríguez</h4>
                                <p class="text-muted">Engineer of OSBB "Heroiv Dnipra 4"</p>
                                <p><i class="bi bi-at color-marker-blue"></i><a href="mailto:osbbhd4@gmail.com" class="text-reset text-decoration-none"> osbbhd4@gmail.com</a></p>
                                <p><i class="bi bi-telephone color-marker-blue"></i> (097) 777-77-77</p>
                                <p><i class="bi bi-watch color-marker-blue"></i> 9.00 - 18.00, Mon - Fri</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>

        <#include "footer.ftlh">
    </body>
</html>