<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="icon" href="../images/favicon.svg">
        <link rel="stylesheet" href="../css/bootstrap-icons.css">
        <link rel="stylesheet" href="../css/bootstrap.min.css">
        <link rel="stylesheet" href="../css/custom_styles.css">
        <title>OSBB HD4 | 500</title>
    </head>

    <body>
        <#include "../header.ftlh">

        <main>
            <div class="container">
                <div>
                    <img src="/images/500.gif" class="d-block m-auto" alt="internal_server_error">
                </div>
            </div>
        </main>

        <#include "../footer.ftlh">
    </body>
</html>