INSERT INTO users_info(user_id, apartment_id, last_name, first_name, patronymic)
VALUES
    (1, null, 'ADMIN', null, null),
    (2, 1, 'Koval', 'Mykola', 'Vasylovych'),
    (3, 2, 'Linkoln', 'Abraham', null),
    (4, 70, 'Tyshchenko', 'Andrii', null),
    (5, 3, 'Baxter', 'Giacomo', null),
    (6, 4, 'Donnelli', 'Bernard', null),
    (7, 5, 'Rice', 'Kennan', null),
    (8, 6, 'Steele', 'Noelani', null),
    (9, 7, 'Smith','Abbot', null),
    (10, 8, 'Aguirre', 'Basil', null),
    (11, 9, 'Vaughan', 'Ciaran', null),
    (12, 10, 'Montoya', 'Berk', null),
    (13, 11, 'Rodriguez', 'Lara', null),
    (14, 12, 'Carney', 'Joshua', null),
    (15, 13, 'Neal', 'Garrison', null),
    (16, 14, 'Valdez','Hedy', null),
    (17, 15, 'Workman','Eugenia', null),
    (18, 16, 'Bentley','Kaitlin', null),
    (19, 17, 'Randolph', 'Kasimir', null),
    (20, 18, 'Daugherty', 'Nolan', null),
    (21, 19, 'Bush', 'Ann', null),
    (22, 20, 'Torrance', 'John "Jack"', 'Daniel Edward'),
    (23, 21, 'Vasquez', 'Gage', null),
    (24, 22, 'Savage', 'Conan', null),
    (25, 23, 'Burt', 'Abigail', null),
    (26, 24, 'Lecter', 'Hannibal', 'VIII'),
    (27, 25, 'Dunn', 'Melissa', null),
    (28, 26, 'Foley', 'Tyrone', null),
    (29, 27, 'Rodriquez', 'Abdul', null),
    (30, 28, 'Mr. Burns', 'Charles', 'Montgomery'),
    (31, 29, 'Phelps', 'Aileen', null),
    (32, 30, 'Baxter', 'Charles', null),
    (33, 31, 'Herrera', 'Melanie', null),
    (34, 32, 'Moriarty', 'James', 'professor'),
    (35, 33, 'Davidson', 'Declan', null),
    (36, 34, 'Phelps', 'Martin', null),
    (37, 35, 'Page', 'Evangeline', null),
    (38, 36, 'Fu Manchu', 'Dr.', null),
    (39, 108, 'Hendricks', 'Minerva', null),
    (40, 144, 'Dorsey', 'Tana', null);